[package]
name = "testing"
version = "0.1.0"
edition = "2024"

[dependencies]
account = { path = "../account" }
network = { path = "../network" }
tokio = { version = "1.49.0", features = ["rt", "rt-multi-thread"] }
